### ISSUE TITLE
not work recent days

### ISSUE THREAD

**Issue by datnqvn** [nightmode/sprucemarks#20]
It worked fine however recent days it seem like doesn't work.
Windows 10 + Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by nightmode** [comment]
Can you try disabling all your Chrome extensions except Sprucemarks. Do a restart of Chrome too for good measure. Then see if Sprucemarks is working like you expect. If it is, start enabling your other Chrome extensions, one by one, to see if Sprucemarks and another extension do not play nice together.

Let me know how the above goes.

**Comment by nightmode** [comment]
No further info to go on. Closing.
