### ISSUE TITLE
Bookmarks sub-menu not being sorted alphabetically

### ISSUE THREAD

**Issue by Pbryanw** [nightmode/sprucemarks#21]
Hi, I've recently started using Chrome again, so I imported my bookmarks from Firefox a few days ago.

All my bookmarks appear to have been sorted alphabetically by Sprucemarks, apart from one sub-menu of Other bookmarks. 

I've attached a picture of it to this post, with the "Boy Meets Girl..." bookmark appearing at the bottom of this menu, instead of near the top.
![Sprucemarks Failure](https://user-images.githubusercontent.com/7268674/61672515-d43f9080-ace3-11e9-8441-803f356cc1fa.png)

I've just wondering if this is a problem on my end, or an issue with Sprucemarks?

Thanks for your help, Pbryanw

**Comment by nightmode** [comment]
Hi Pbryanw. ^_^

I found the URL https://itunes.apple.com/gb/tv-season/boy-meets-girl-series-1/id1033178264 and after bookmarking it, experienced the exact same issue.

Seems like there is some kind of invisible character right before the B in Boy on that page. Either that or Chrome is prepending an invisible character when creating the bookmark but that seems less likely.

To fix the bookmark, edit it, go to absolute left most of the line and then keep pressing the DEL key until the B disappears. You'll probably have to press DEL twice which will confirm the presence of the invisible character. Then add a new B and save your changes. Now your bookmarks should be sorted. ^_^

**Comment by Pbryanw** [comment]
Hi nightmode,

Thanks for your quick reply, and help with this.

I can confirm that deleting the existing "B" in "Boy Meets Girl..." then re-entering it again, works for me as well 👍 :-)

That's great! Thanks again for your help 👍 

Kind regards, Pbryanw.
