### ISSUE TITLE
Bookmarks and folders directly in 'Other bookmarks' are not being sorted despite 'Sort Other Bookmarks' setting

### ISSUE THREAD

**Issue by Kaedin** [nightmode/sprucemarks#22]
Hi Dev,

I just recently came across a following issue that bookmarks and folders located directly in 'Other bookmarks' are not being sorted despite 'Sort Other Bookmarks' setting is turned on. However, 'Sort Other Bookmarks Sub Folders' setting works still.

![image](https://user-images.githubusercontent.com/26382655/64091119-644b0e00-cd57-11e9-93e9-2d11ae8ee52a.png)

![image](https://user-images.githubusercontent.com/26382655/64091056-159d7400-cd57-11e9-9616-a883ca216128.png)

![image](https://user-images.githubusercontent.com/26382655/64091094-42ea2200-cd57-11e9-8739-a470de004795.png)

Observed on Chrome version 76.0.3809.132 (Official Build) (64-bit). Kindly let me know if you need any additional information.

Best regards,
Kaedin

**Comment by nightmode** [comment]
Hi Kaedin,

Thanks for the screenshots. That definitely looks like something is wrong.

Can you tell me what OS and version of OS you are running on?

I'm using the same Chrome version on macOS Mojave and when I drag a root level bookmark in my "Other Bookmarks" folder it closes the bookmark popup and then when I open "Other Bookmarks" again, everything is sorted as expected. I'm guessing if you do the same procedure by moving a bookmark under "Other Bookmarks", that bookmark just stays wherever you last left it?

**Comment by Kaedin** [comment]
Hi @nightmode,

Actually there is no issue after all! Maybe I was in a need of my morning coffee to get my head working...

Somehow, I had placed all the folders and bookmarks, which usually resided in 'Other bookmarks', actually into the 'Boomarks bar' and thought I was browsing 'Other bookmarks' instead through the expansion button.

Sorry for confusion and false alarm here!

**Comment by nightmode** [comment]
A happy ending so no worries here. ^_^

❤️ ☕️
