### ISSUE TITLE
Order of Folders with Underscore Character

### ISSUE THREAD

**Issue by GaryEarthling** [nightmode/sprucemarks#23]
I'm experiencing odd behaviour with the sorting of folders that have an underscore character in the name. With the names in the attached screenshot, I would expect "__aaaNewFolder" to be first, followed by "_2019-11 ...". 

The "Sort Bookmarks Bar" and "Sort Bookmarks Sub Folders" options are both checked with the "A-Z" option selected. The "Delay Sorting" option is also unchecked if that makes any difference.

Am I doing something wrong? Chrome version is 78.0.3904.87 (Official Build) (64-bit).

![screenshot](https://user-images.githubusercontent.com/54581080/68205893-602aaf00-ff99-11e9-8967-4c4dd86a0881.jpg)

**Comment by nightmode** [comment]
The current sorting logic has underscore come later but I do like the convention of underscores coming first. Just like it does using macOS Finder Windows File Explorer.

Going to leave this issue open for now as a reminder to myself.

**Comment by GaryEarthling** [comment]
If you need another reason to make underscores come first, numbers and letters seem to be treated differently currently. Underscore comes last with numbers but first with letters. See attached screenshot.

Given these names, Windows would put all underscores first, followed by numbers, then letters. Not sure about Mac.

![screenshot](https://user-images.githubusercontent.com/54581080/69574177-8a1e3280-0f95-11ea-8243-308b2151f011.jpg)

**Comment by nightmode** [comment]
Great screenshot!

There are some major changes coming to Sprucemarks and improving the default sort is going to be part of those changes. Thank you for documenting this. ^_^

**Comment by GaryEarthling** [comment]
Awesome, thanks nightmode!  I'll look out for the next version. Thanks for taking the time to comment ... and for making such an awesome extension!

**Comment by nightmode** [comment]
I've cloned this issue into the private version of the Sprucemarks repo which is where all the upcoming Patreon changes are being made.

Thanks again for reporting this Gary. ^_^
